spring:
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
    username: rm99572
    password: 180303
  jpa:
    hibernate:
      ddl-auto: update
open-in-view: false
show-sql: tru
